import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import AppTopbar from "@/components/layout/app-topbar";
import AppSidebar from "@/components/layout/app-sidebar";
import PageContainer from "@/components/layout/page-container";
import { SidebarProvider } from "@/contexts/sidebar-context";
import DraggableCTA from "@/components/shared/cta-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Content Workspace",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <SidebarProvider>
        <div className="flex min-h-screen">
          <AppSidebar />
          <div className="flex flex-1 flex-col">
            <AppTopbar />
            <PageContainer>
              <>
                <DraggableCTA />
                {children}
              </>
            </PageContainer>
          </div>
        </div>
      </SidebarProvider>
    </div>
  );
}
